{{- define "_dockerconfigjson" -}}
{{ include "_dockerconfigjson.yaml" . | b64enc }}
{{- end }}

{{- define "_dockerconfigjson.yaml" -}}
{{- with .Values.imagePullSecret -}}
{
  "auths": {
    {{ .registry | default "https://index.docker.io/v1/" | quote }}: {
      "username": {{ .username | quote }},
      "password": {{ .password | quote }},
      {{- if .email }}
      "email": {{ .email | quote }},
      {{- end }}
      "auth": {{ (print .username ":" .password) | b64enc | quote }}
    }
  }
}
{{- end }}
{{- end }}

{{- if .Values.imagePullSecret.create -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.imagePullSecret.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "_dockerconfigjson" . }}
{{- end }}
