name: Lint and Validate helm chart

on:
  pull_request:
    paths:
      - "**/*.yaml"
      - "**/*.yml"

env:
  HELM_VERSION: "v3.9.0"

jobs:
  yamllint-config:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      - name: Install yamllint
        run: pip install yamllint

      # We use --no-warnings to reduce output to critical errors
      - name: Run yamllint
        run: yamllint -d scripts/yamllint-no-secrets.yaml --no-warnings .

  lint-helm:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
        # versions must be available
        # at https://github.com/instrumenta/kubernetes-json-schema
        # in the form v${version}-standalone-strict
        # this does *not* include all kubernetes versions!
        #
        # FIXME: 1.18.1 was the latest, and now this project is stale. See
        # https://github.com/jupyterhub/mybinder.org-deploy/issues/2206.
        #
        - release: staging
          kube_version: "1.18.1"
        - release: prod
          kube_version: "1.18.1"
        - release: ovh
          kube_version: "1.18.1"
        - release: turing
          kube_version: "1.18.1"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install and setup helm ${{ env.HELM_VERSION }}
        run: |
          curl -sf https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | DESIRED_VERSION=${HELM_VERSION} bash
          helm dependency update ./mybinder
          helm plugin install https://github.com/instrumenta/helm-kubeval

      - name: Run chartpress to update values.yaml
        run: chartpress --skip-build

      - name: Run helm kubeval for ${{ matrix.release }} with kube-${{ matrix.kube_version }}
        run: |
          # add `--values=config/common/x.yaml --values=config/common/y.yaml` etc.
          # to load all common config files
          common_config=$(ls config/common/*.yaml | awk '{print "--values=" $1}')
          helm kubeval \
            --kubernetes-version ${{ matrix.kube_version }} \
            --strict \
            --ignore-missing-schemas \
            ${common_config} \
            --values=config/${{ matrix.release }}.yaml \
            --values=config/test-secrets.yaml \
            mybinder
